sudo: required
services:
    - docker

before_install:
    - docker build -t navneet2014/react-project -f Dockerfile_dev .

script:
    - docker run -e CI=true navneet2014/react-project npm run test

deploy:
    provider: elasticbeanstalk
    region: ap-south-1 # Specify your region
    app: "react-project-docker-test" # Copy it from Elastic Beanstalk dashboard
    env: "ReactProjectDockerTest-env" # Copy it from Elastic Beanstalk dashboard
    bucket_name: "elasticbeanstalk-ap-south-1-825746486758"
    bucket_path: "docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master
